version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:21.0'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

executors:
  j19:
    docker:
      - image: 'cimg/openjdk:21.0'

orbs:
  maven: circleci/maven@1.4.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: j19
      - build:
          context: SonarCloud